baseURL: "https://www.covid19dataportal.ee/"
title: "COVID-19 Data Portal Estonia"
params:
  title: "COVID-19 Data Portal Estonia"
  description: COVID-19 Data Portal for Estonian Research
  images:
    - /img/site_logo/CDP-19_Estonia.png

  # There is a hugo i18n package, but it seems like overkill for so few strings
  lang_strings:
    en:
      home_title: Accelerating research through data sharing
      enquire_email_footer_dc: "Contact the Swedish COVID-19 Data Portal"
      enquire_email_footer_bioinformatics: "For bioinformatics support, please contact"
      support_feedback: Support & Feedback
      privacy: Privacy Notice
      github_link: Website code on GitHub
      skip_to_content: Skip to main content
      readmore_text: Read more
      published_text: Published
      all_highlights: See all data highlights
      next_highlight: Next
      previous_highlight: Previous
      dt_project: Project
      dt_last_updated: Last updated
      dt_available_data: Available data
      dt_data_types: Data types
      dt_entries_in_total: entries in total
      projects_title: Project title
      projects_area: Area
      projects_pi: Principal investigator
      projects_piaff: PI affiliation
      projects_duration: Duration
      projects_funder: Funder
      menu_moretypes: More
      menu_biobanks: Biobanks
      menu_projects: Research projects
      pubs_pub: Publication
      pubs_updated: Published
      pubs_field: Field/Topic
      pubs_availability: Data availability
      pubs_type: Publication type
      pubs_year: Year
      pubs_funder: Funder
    ee:
      home_title: Teadusele hoogu juurde läbi andmete jagamise
      enquire_email_footer_dc: "Võta Eesti Covid-19 andmeportaaliga ühendust"
      enquire_email_footer_bioinformatics: "Bioinformaatika alase abi saamiseks, kontakteeru"
      support_feedback: Küsimused ja tagasiside
      privacy: Privaatsuspoliitika
      github_link: Veebilehe kood GitHubis
      skip_to_content: Tagasi põhilehele
      readmore_text: Loe rohkem
      published_text: Avaldatud
      all_highlights: Vaata esile tõstetud andmeid
      next_highlight: Järgmine
      previous_highlight: Eelmine
      dt_project: Projekt
      dt_last_updated: Viimati uuendatud
      dt_available_data: Avalikud andmed
      dt_data_types: Andmetüübid
      dt_entries_in_total: kokku tulemusi
      projects_title: Projekti pealkiri
      projects_area: Teadussuund
      projects_pi: Projektijuht
      projects_piaff: Organisatsioon
      projects_duration: Algus- ja lõpukuupäev
      projects_funder: Rahastaja
      menu_moretypes: Rohkem
      menu_biobanks: Biobangad
      menu_projects: Teadusprojektid
      pubs_pub: Publikatsioon
      pubs_updated: Avaldatud
      pubs_field: Teemavaldkond
      pubs_availability: Andmete kättesaadavus
      pubs_type: Publikatsiooni tüüp
      pubs_year: Aasta
      pubs_funder: Rahastaja

languages:
  en:
    languageName: English
    contentDir: content/english
    weight: 1

  ee:
    languageName: Eesti
    contentDir: content/eesti
    weight: 2
    description: Covid-19 andmeportaal

markup:
  goldmark:
    renderer:
      unsafe: true
