baseURL: "https://www.covid19dataportal.se/"
title: "COVID-19 Data Portal Sweden"
params:
  title: "COVID-19 Data Portal Sweden"
  description: COVID-19 Data Portal for Swedish Research
  images:
    - /img/site_logo/CV19DP_logo_social_card_SWE.png

  # There is a hugo i18n package, but it seems like overkill for so few strings
  lang_strings:
    en:
      home_title: Accelerating research through data sharing
      enquire_email_footer_dc: "Contact the Swedish COVID-19 Data Portal"
      enquire_email_footer_bioinformatics: "For bioinformatics support, please contact"
      support_feedback: Support & Feedback
      privacy: Privacy Notice
      github_link: Website code on GitHub
      skip_to_content: Skip to main content
      readmore_text: Read more
      published_text: Published
      dt_project: Project
      dt_last_updated: Last updated
      dt_available_data: Available data
      dt_data_types: Data types
      dt_entries_in_total: entries in total
    sv:
      home_title: Snabbare forskning genom datadelning
      enquire_email_footer_dc: "Kontakta den svenska Covid-19 dataportalen"
      enquire_email_footer_bioinformatics: "För support inom bioinformatik, kontakta"
      support_feedback: Support och Feedback
      privacy: Integritetspolicy
      github_link: Webbplatskod på GitHub
      skip_to_content: Hoppa till innehållet
      readmore_text: Läs mer
      published_text: Publicerad
      dt_project: Projekt
      dt_last_updated: Senast uppdaterad
      dt_available_data: Tillgängliga data
      dt_data_types: Datatyper
      dt_entries_in_total: resultat

languages:
  en:
    languageName: English
    contentDir: content/english
    weight: 1
    menu:
      top_nav:
        - name: European Portal
          url: https://www.covid19dataportal.org/
          weight: 20

  sv:
    languageName: Svenska
    contentDir: content/svenska
    weight: 2
    description: COVID-19 Dataportal för svensk forskning
    menu:
      top_nav:
        - name: Europeiska portalen
          url: https://www.covid19dataportal.org/
          weight: 20

markup:
  goldmark:
    renderer:
      unsafe: true
